---
name: Check Java Code
on:
  pull_request:
  workflow_dispatch:
jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_java
        with:
          version: 11

      - name: Check Code Formatting
        run: |
          sh ./style-guide/google-format-ci-v0.1.sh
        env:
          GOOGLE_JAR_VERSION: 1.11.0
          GOOGLE_JAR_NAME: google-java-format-1.11.0-all-deps.jar

      - name: Checkstyle
        run: |
          pushd src/scheduler
            mvn --no-transfer-progress jxr:jxr
            mvn --no-transfer-progress checkstyle:checkstyle
          popd

      - name: Publish Results on Pull Request
        run: |
          go run format_checkstyle.go

  sonar-cloud:
    env:
      DB_DATABASE: autoscaler
      DB_USER: postgres
      DB_PASSWORD: postgres
    name: Sonar Cloud
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscaler
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis with SonarCloud
      - uses: ./.github/actions/setup_go
      - uses: ./.github/actions/setup_java
        with:
          version: 11

      - name: Build
        run: |
          make build

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          make prepare-scheduler-test
          pushd src/scheduler
            mvn --no-transfer-progress test spotbugs:spotbugs org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          popd
